# -*- coding: utf-8 -*-
"""Taller Cubo de rubik

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19L32f6kwIoGYZr_P7klJLV_77D61yQ4T

### Implementación de la Clase `RubiksCube`

Para poder aplicar los algoritmos de búsqueda, primero necesitamos una representación funcional del cubo de Rubik. Esta clase `RubiksCube` manejará:

*   La representación del estado del cubo (6 caras, cada una con 9 pegatinas).
*   Los 18 movimientos posibles (U, D, L, R, F, B y sus variantes en sentido horario, antihorario y doble giro).
*   La capacidad de mezclar el cubo (`scramble`).
*   La verificación de si el cubo está resuelto (`is_solved`).
*   Una forma de obtener un estado `hashable` para usar en los algoritmos de búsqueda.
*   Una forma de visualizar el cubo.

Los colores de las caras en estado resuelto se asignarán convencionalmente:
*   **U (Arriba):** Blanco (`'W'`)
*   **F (Frente):** Verde (`'G'`)
*   **R (Derecha):** Rojo (`'R'`)
*   **B (Atrás):** Azul (`'B'`)
*   **L (Izquierda):** Naranja (`'O'`)
*   **D (Abajo):** Amarillo (`'Y'`)
"""

import collections
import time
import random

class RubiksCube:
    def __init__(self, state=None):
        # Define el estado resuelto inicial usando un diccionario de caras de 3x3
        # Cada cara es una lista de listas que representan su cuadrícula de pegatinas de 3x3.
        self.faces = {
            'U': [['W'] * 3 for _ in range(3)],  # Arriba (Blanco)
            'F': [['G'] * 3 for _ in range(3)],  # Frente (Verde)
            'R': [['R'] * 3 for _ in range(3)],  # Derecha (Rojo)
            'B': [['B'] * 3 for _ in range(3)],  # Atrás (Azul)
            'L': [['O'] * 3 for _ in range(3)],  # Izquierda (Naranja)
            'D': [['Y'] * 3 for _ in range(3)]   # Abajo (Amarillo)
        }
        if state: # Si se proporciona un estado inicial (por ejemplo, de un cubo mezclado)
            self.faces = self._state_to_faces(state)

        # Diccionario que mapea cadenas de movimientos a sus métodos correspondientes
        self.moves = {
            'U': self._U, "U'": self._U_prime, 'U2': self._U2,
            'D': self._D, "D'": self._D_prime, 'D2': self._D2,
            'L': self._L, "L'": self._L_prime, 'L2': self._L2,
            'R': self._R, "R'": self._R_prime, 'R2': self._R2,
            'F': self._F, "F'": self._F_prime, 'F2': self._F2,
            'B': self._B, "B'": self._B_prime, 'B2': self._B2,
        }

    def _state_to_faces(self, state_tuple):
        # Ayuda a convertir una tupla de estado hashable de nuevo a un diccionario de caras
        # Asume que state_tuple está ordenado U, F, R, B, L, D como en get_state()
        faces_dict = {}
        face_keys_order = ['U', 'F', 'R', 'B', 'L', 'D']
        for i, face_key in enumerate(face_keys_order):
            faces_dict[face_key] = [list(row) for row in state_tuple[i]]
        return faces_dict

    def _rotate_face_clockwise(self, face_key):
        # Rota una matriz de cara de 3x3 en sentido horario
        face = self.faces[face_key]
        self.faces[face_key] = [list(row) for row in zip(*face[::-1])]

    def _rotate_face_counter_clockwise(self, face_key):
        # Rota una matriz de cara de 3x3 en sentido antihorario
        face = self.faces[face_key]
        self.faces[face_key] = [list(row) for row in zip(*face)][::-1]

    # --- Movimientos de Cara Principales --- (Rotaciones en sentido horario y cambios de capa adyacente)

    def _U(self):
        self._rotate_face_clockwise('U')
        # Desplaza las filas superiores de las caras F, R, B, L
        temp = list(self.faces['F'][0]) # Almacena la fila superior de F
        self.faces['F'][0] = list(self.faces['R'][0])
        self.faces['R'][0] = list(self.faces['B'][0])
        self.faces['B'][0] = list(self.faces['L'][0])
        self.faces['L'][0] = temp

    def _U_prime(self):
        self._rotate_face_counter_clockwise('U')
        # Desplaza las filas superiores en sentido antihorario
        temp = list(self.faces['F'][0])
        self.faces['F'][0] = list(self.faces['L'][0])
        self.faces['L'][0] = list(self.faces['B'][0])
        self.faces['B'][0] = list(self.faces['R'][0])
        self.faces['R'][0] = temp

    def _U2(self):
        self._U(); self._U() # Doble movimiento U

    def _D(self):
        self._rotate_face_clockwise('D')
        # Desplaza las filas inferiores de las caras F, L, B, R
        temp = list(self.faces['F'][2]) # Almacena la fila inferior de F
        self.faces['F'][2] = list(self.faces['L'][2])
        self.faces['L'][2] = list(self.faces['B'][2])
        self.faces['B'][2] = list(self.faces['R'][2])
        self.faces['R'][2] = temp

    def _D_prime(self):
        self._rotate_face_counter_clockwise('D')
        # Desplaza las filas inferiores en sentido antihorario
        temp = list(self.faces['F'][2])
        self.faces['F'][2] = list(self.faces['R'][2])
        self.faces['R'][2] = list(self.faces['B'][2])
        self.faces['B'][2] = list(self.faces['L'][2])
        self.faces['L'][2] = temp

    def _D2(self):
        self._D(); self._D()

    def _L(self):
        self._rotate_face_clockwise('L')
        # Desplaza las columnas izquierdas de U, F, D, y la columna derecha de B
        temp_U_col = [self.faces['U'][i][0] for i in range(3)] # Almacena la columna izquierda de U
        for i in range(3):
            self.faces['U'][i][0] = self.faces['F'][i][0]
            self.faces['F'][i][0] = self.faces['D'][i][0]
            self.faces['D'][i][0] = self.faces['B'][2 - i][2] # La columna izquierda de D toma la columna derecha de B (invertida)
            self.faces['B'][i][2] = temp_U_col[2 - i] # La columna derecha de B toma la columna izquierda de U (invertida)

    def _L_prime(self):
        self._rotate_face_counter_clockwise('L')
        # Desplaza las columnas izquierdas de U, D, F, y la columna derecha de B en sentido antihorario
        temp_U_col = [self.faces['U'][i][0] for i in range(3)] # Almacena la columna izquierda de U
        for i in range(3):
            self.faces['U'][i][0] = self.faces['B'][2 - i][2] # La columna izquierda de U toma la columna derecha de B (invertida)
            self.faces['B'][i][2] = self.faces['D'][2 - i][0] # La columna derecha de B toma la columna izquierda de D (invertida)
            self.faces['D'][i][0] = self.faces['F'][i][0]
            self.faces['F'][i][0] = temp_U_col[i]

    def _L2(self):
        self._L(); self._L()

    def _R(self):
        self._rotate_face_clockwise('R')
        # Desplaza las columnas derechas de U, F, D, y la columna izquierda de B
        temp_U_col = [self.faces['U'][i][2] for i in range(3)] # Almacena la columna derecha de U
        for i in range(3):
            self.faces['U'][i][2] = self.faces['B'][2 - i][0] # La columna derecha de U toma la columna izquierda de B (invertida)
            self.faces['B'][i][0] = self.faces['D'][2 - i][2] # La columna izquierda de B toma la columna derecha de D (invertida)
            self.faces['D'][i][2] = self.faces['F'][i][2]
            self.faces['F'][i][2] = temp_U_col[i]

    def _R_prime(self):
        self._rotate_face_counter_clockwise('R')
        # Desplaza las columnas derechas en sentido antihorario
        temp_U_col = [self.faces['U'][i][2] for i in range(3)] # Almacena la columna derecha de U
        for i in range(3):
            self.faces['U'][i][2] = self.faces['F'][i][2]
            self.faces['F'][i][2] = self.faces['D'][i][2]
            self.faces['D'][i][2] = self.faces['B'][2 - i][0] # La columna derecha de D toma la columna izquierda de B (invertida)
            self.faces['B'][i][0] = temp_U_col[2 - i] # La columna izquierda de B toma la columna derecha de U (invertida)

    def _R2(self):
        self._R(); self._R()

    def _F(self):
        self._rotate_face_clockwise('F')
        # Desplaza la fila inferior de U, la columna derecha de L, la fila superior de D, la columna izquierda de R
        temp_U_row = list(self.faces['U'][2]) # Almacena la fila inferior de U
        # La parte inferior de U va a la izquierda de R
        for i in range(3):
            self.faces['U'][2][i] = self.faces['L'][2 - i][2] # La fila inferior de U toma la columna derecha de L (invertida)
        # La parte derecha de L va a la parte superior de D
        for i in range(3):
            self.faces['L'][i][2] = self.faces['D'][0][i] # La columna derecha de L toma la fila superior de D
        # La parte superior de D va a la izquierda de R
        for i in range(3):
            self.faces['D'][0][i] = self.faces['R'][2 - i][0] # La fila superior de D toma la columna izquierda de R (invertida)
        # La parte izquierda de R va a la parte inferior de U
        for i in range(3):
            self.faces['R'][i][0] = temp_U_row[i]

    def _F_prime(self):
        self._rotate_face_counter_clockwise('F')
        # Desplaza las capas en sentido antihorario
        temp_U_row = list(self.faces['U'][2])
        for i in range(3):
            self.faces['U'][2][i] = self.faces['R'][i][0]
            self.faces['R'][i][0] = self.faces['D'][0][2 - i] # La columna izquierda de R toma la fila superior de D (invertida)
            self.faces['D'][0][i] = self.faces['L'][i][2]
            self.faces['L'][i][2] = temp_U_row[2 - i] # La columna derecha de L toma la fila inferior de U (invertida)

    def _F2(self):
        self._F(); self._F()

    def _B(self):
        self._rotate_face_clockwise('B')
        # Desplaza la fila superior de U, la columna izquierda de R, la fila inferior de D, la columna derecha de L
        temp_U_row = list(self.faces['U'][0]) # Almacena la fila superior de U
        # La parte superior de U va a la derecha de L
        for i in range(3):
            self.faces['U'][0][i] = self.faces['R'][i][2] # La fila superior de U toma la columna derecha de R
        # La parte derecha de R va a la parte inferior de D
        for i in range(3):
            self.faces['R'][i][2] = self.faces['D'][2][2 - i] # La columna derecha de R toma la fila inferior de D (invertida)
        # La parte inferior de D va a la izquierda de L
        for i in range(3):
            self.faces['D'][2][i] = self.faces['L'][i][0] # La fila inferior de D toma la columna izquierda de L
        # La parte izquierda de L va a la parte superior de U
        for i in range(3):
            self.faces['L'][i][0] = temp_U_row[2 - i] # La columna izquierda de L toma la fila superior de U (invertida)

    def _B_prime(self):
        self._rotate_face_counter_clockwise('B')
        # Desplaza las capas en sentido antihorario
        temp_U_row = list(self.faces['U'][0])
        for i in range(3):
            self.faces['U'][0][i] = self.faces['L'][2 - i][0] # La fila superior de U toma la columna izquierda de L (invertida)
            self.faces['L'][i][0] = self.faces['D'][2][i]
            self.faces['D'][2][i] = self.faces['R'][2 - i][2] # La fila inferior de D toma la columna derecha de R (invertida)
            self.faces['R'][i][2] = temp_U_row[i]

    def _B2(self):
        self._B(); self._B()

    def apply_move(self, move_str):
        """Aplica un solo movimiento al cubo."""
        if move_str in self.moves:
            self.moves[move_str]()
        else:
            raise ValueError(f"Movimiento desconocido: {move_str}")

    def get_state(self):
        """Devuelve una representación hashable del estado del cubo."""
        # Aplana todas las caras en una tupla de tuplas (para hacerla hashable)
        # Orden consistente para el hash: U, F, R, B, L, D
        state_representation = []
        for face_key in ['U', 'F', 'R', 'B', 'L', 'D']:
            state_representation.append(tuple(tuple(sticker for sticker in row) for row in self.faces[face_key]))
        return tuple(state_representation)

    def is_solved(self):
        """Verifica si el cubo está en el estado resuelto."""
        solved_colors = {
            'U': 'W', 'F': 'G', 'R': 'R', 'B': 'B', 'L': 'O', 'D': 'Y'
        }
        for face_key, target_color in solved_colors.items():
            for row in self.faces[face_key]:
                for sticker in row:
                    if sticker != target_color:
                        return False
        return True

    def scramble(self, num_moves=20):
        """Aplica una secuencia de movimientos aleatorios para mezclar el cubo."""
        possible_moves = list(self.moves.keys())
        # Excluye movimientos dobles (U2, D2, etc.) de la mezcla aleatoria por ahora para mantenerlo simple
        # y evitar deshacer un movimiento inmediatamente, aunque eso está bien para mezclar.
        # Usemos solo movimientos básicos U, U', D, D', etc., para la mezcla para una mejor distribución.
        basic_moves = [m for m in possible_moves if not m.endswith('2')]

        scramble_sequence = [random.choice(basic_moves) for _ in range(num_moves)]
        for move in scramble_sequence:
            self.apply_move(move)
        return scramble_sequence

    def display(self):
        """Una visualización simple del cubo basada en texto para depuración."""
        # Ayudante para imprimir una fila centrada para las caras U/D
        def print_face_row(row_data, indent=6):
            print(" " * indent + " ".join(row_data))

        # Cara U
        print("\n--- Estado del Cubo de Rubik ---")
        print_face_row(self.faces['U'][0])
        print_face_row(self.faces['U'][1])
        print_face_row(self.faces['U'][2])

        # Caras L F R B (una al lado de la otra)
        for i in range(3):
            print(" ".join(self.faces['L'][i]) + " " +
                  " ".join(self.faces['F'][i]) + " " +
                  " ".join(self.faces['R'][i]) + " " +
                  " ".join(self.faces['B'][i]))

        # Cara D
        print_face_row(self.faces['D'][0])
        print_face_row(self.faces['D'][1])
        print_face_row(self.faces['D'][2])
        print("--------------------------")

    def __str__(self):
        """Proporciona una representación compacta en cadena del estado del cubo."""
        s = ""
        # Define un orden consistente para la representación en cadena: U, F, R, B, L, D
        for face_key in ['U', 'F', 'R', 'B', 'L', 'D']:
            for row in self.faces[face_key]:
                s += "".join(row)
        return s

    def __hash__(self):
        """Permite el hash de objetos RubiksCube basado en su cadena de estado."""
        return hash(self.__str__()) # Hash basado en la representación de cadena compacta

    def __eq__(self, other):
        """Define la comparación de igualdad para objetos RubiksCube."""
        if not isinstance(other, RubiksCube):
            return NotImplemented
        return self.__str__() == other.__str__()

"""### Prueba de la Clase `RubiksCube`

Vamos a crear un cubo, mezclarlo y mostrar su estado para verificar que la implementación básica funciona correctamente.
"""

# 1. Crear un cubo resuelto
solved_cube = RubiksCube()
print("Cubo Resuelto (Estado Inicial):")
solved_cube.display()
print(f"¿Está resuelto? {solved_cube.is_solved()}")

# 2. Mezclar el cubo con 10 movimientos aleatorios
scrambled_cube = RubiksCube()
scramble_sequence = scrambled_cube.scramble(10)
print(f"\nCubo Mezclado (10 movimientos):\nSecuencia: {scramble_sequence}")
scrambled_cube.display()
print(f"¿Está resuelto? {scrambled_cube.is_solved()}")

# 3. Aplicar un movimiento específico al cubo mezclado
print("\nAplicando movimiento 'F' al cubo mezclado...")
scrambled_cube.apply_move('F')
scrambled_cube.display()
print(f"¿Está resuelto? {scrambled_cube.is_solved()}")

# 4. Crear un cubo a partir de un estado existente (para pruebas de hash/igualdad)
cube1 = RubiksCube()
cube1.apply_move('U')
cube1.apply_move('R')

cube2 = RubiksCube(state=cube1.get_state()) # Crea un nuevo cubo a partir del estado de cube1

print("\nCubo 1 (U R):")
cube1.display()
print("Cubo 2 (copia del estado de Cubo 1):")
cube2.display()

print(f"¿Cubo 1 == Cubo 2? {cube1 == cube2}")
print(f"Hash de Cubo 1: {hash(cube1)}")
print(f"Hash de Cubo 2: {hash(cube2)}")

"""### A. Búsqueda en Profundidad (DFS)

La Búsqueda en Profundidad (DFS) explora lo más lejos posible a lo largo de cada rama antes de retroceder. Utiliza una pila para almacenar los nodos a visitar y una estructura para registrar los nodos ya visitados y evitar ciclos. Es importante notar que DFS no garantiza encontrar el camino más corto.
"""

class Node:
    def __init__(self, state, parent=None, move=None, depth=0):
        self.state = state
        self.parent = parent
        self.move = move
        self.depth = depth # Añadir atributo de profundidad

    def get_path(self):
        path = []
        current = self
        while current.move is not None:
            path.append(current.move)
            current = current.parent
        return path[::-1] # Invertir para obtener los movimientos de inicio a fin

def dfs_solve(start_cube, max_depth=7): # Parámetro max_depth añadido
    start_time = time.time()

    # Usar get_state() del cubo para una representación hashable
    initial_state_tuple = start_cube.get_state()
    initial_node = Node(initial_state_tuple, depth=0)

    stack = collections.deque([initial_node])  # Pila para DFS
    visited = {initial_state_tuple} # Conjunto para rastrear estados visitados

    nodes_visited_count = 0

    while stack:
        current_node = stack.pop()
        nodes_visited_count += 1

        if current_node.depth >= max_depth: # Verificación de límite de profundidad
            continue

        # Crear un objeto cubo temporal a partir del estado del nodo actual
        temp_cube = RubiksCube(current_node.state)

        if temp_cube.is_solved():
            end_time = time.time()
            execution_time_ms = (end_time - start_time) * 1000
            return {
                "time_ms": execution_time_ms,
                "nodes_visited": nodes_visited_count,
                "solution_path": current_node.get_path()
            }

        for move_name in temp_cube.moves.keys():
            # Crear un nuevo cubo para cada movimiento potencial para evitar modificar temp_cube in situ
            next_cube = RubiksCube(current_node.state)
            next_cube.apply_move(move_name)
            next_state_tuple = next_cube.get_state()

            if next_state_tuple not in visited:
                visited.add(next_state_tuple)
                next_node = Node(next_state_tuple, current_node, move_name, current_node.depth + 1)
                stack.append(next_node)

    end_time = time.time()
    execution_time_ms = (end_time - start_time) * 1000
    return {
        "time_ms": execution_time_ms,
        "nodes_visited": nodes_visited_count,
        "solution_path": [] # No se encontró solución
    }

"""### B. Búsqueda en Amplitud (BFS)

La Búsqueda en Amplitud (BFS) explora todos los nodos de un nivel antes de pasar al siguiente. Utiliza una cola para almacenar los nodos a visitar y garantiza encontrar el camino más corto en grafos no ponderados o con aristas de costo uniforme (como es el caso de los movimientos de un cubo de Rubik, donde cada movimiento tiene un costo de 1).
"""

import collections
import time

def bfs_solve(start_cube, max_depth=7):
    start_time = time.time()

    initial_state_tuple = start_cube.get_state()
    initial_node = Node(initial_state_tuple, depth=0)

    queue = collections.deque([initial_node])  # Cola para BFS
    visited = {initial_state_tuple} # Conjunto para rastrear estados visitados

    nodes_visited_count = 0

    while queue:
        current_node = queue.popleft()
        nodes_visited_count += 1

        if current_node.depth >= max_depth: # Verificación de límite de profundidad
            continue

        temp_cube = RubiksCube(current_node.state)

        if temp_cube.is_solved():
            end_time = time.time()
            execution_time_ms = (end_time - start_time) * 1000
            return {
                "time_ms": execution_time_ms,
                "nodes_visited": nodes_visited_count,
                "solution_path": current_node.get_path()
            }

        for move_name in temp_cube.moves.keys():
            next_cube = RubiksCube(current_node.state)
            next_cube.apply_move(move_name)
            next_state_tuple = next_cube.get_state()

            if next_state_tuple not in visited:
                visited.add(next_state_tuple)
                next_node = Node(next_state_tuple, current_node, move_name, current_node.depth + 1)
                queue.append(next_node)

    end_time = time.time()
    execution_time_ms = (end_time - start_time) * 1000
    return {
        "time_ms": execution_time_ms,
        "nodes_visited": nodes_visited_count,
        "solution_path": [] # No se encontró solución
    }

"""### C. Algoritmo de Dijkstra

Dijkstra es un algoritmo para encontrar los caminos más cortos entre los nodos de un grafo, lo que lo hace útil para encontrar la secuencia de movimientos mínima. En el caso del cubo de Rubik, donde cada movimiento tiene un costo uniforme (1), Dijkstra se comporta de manera similar a BFS, garantizando el camino más corto.
"""

import heapq
import time

def dijkstra_solve(start_cube, max_depth=7):
    start_time = time.time()

    initial_state_tuple = start_cube.get_state()
    initial_node = Node(initial_state_tuple, depth=0)

    # La cola de prioridad almacena tuplas: (costo, id_nodo, nodo)
    # id_nodo se usa para desempatar si los costos son iguales, asegurando que los objetos nodo sean distintos en el heap
    priority_queue = [(0, id(initial_node), initial_node)]

    # g_score almacena el costo del camino más barato desde el inicio hasta un estado
    g_score = {initial_state_tuple: 0}

    nodes_visited_count = 0

    while priority_queue:
        cost, _, current_node = heapq.heappop(priority_queue)
        nodes_visited_count += 1

        # Si ya hemos encontrado un camino más barato a este estado, saltar
        if cost > g_score.get(current_node.state, float('inf')):
            continue

        if current_node.depth >= max_depth: # Verificación de límite de profundidad
            continue

        temp_cube = RubiksCube(current_node.state)

        if temp_cube.is_solved():
            end_time = time.time()
            execution_time_ms = (end_time - start_time) * 1000
            return {
                "time_ms": execution_time_ms,
                "nodes_visited": nodes_visited_count,
                "solution_path": current_node.get_path()
            }

        for move_name in temp_cube.moves.keys():
            next_cube = RubiksCube(current_node.state)
            next_cube.apply_move(move_name)
            next_state_tuple = next_cube.get_state()

            # El costo para alcanzar el siguiente estado es el costo actual + 1 (por un movimiento)
            tentative_g_score = g_score[current_node.state] + 1

            if tentative_g_score < g_score.get(next_state_tuple, float('inf')):
                g_score[next_state_tuple] = tentative_g_score
                next_node = Node(next_state_tuple, current_node, move_name, current_node.depth + 1)
                heapq.heappush(priority_queue, (tentative_g_score, id(next_node), next_node))

    end_time = time.time()
    execution_time_ms = (end_time - start_time) * 1000
    return {
        "time_ms": execution_time_ms,
        "nodes_visited": nodes_visited_count,
        "solution_path": [] # No se encontró solución
    }

"""### D. Búsqueda Voraz (Greedy Best-First Search)

La búsqueda voraz utiliza una función heurística para estimar qué tan "cerca" está un estado del objetivo, y siempre expande el nodo que parece más prometedor. No garantiza encontrar el camino más corto, pero puede ser mucho más rápido que BFS o Dijkstra en problemas con una buena heurística. Implementaremos una heurística simple que cuenta la cantidad de pegatinas que no están en su color resuelto para su respectiva cara.
"""

import heapq
import time

def heuristic(cube_state_tuple):
    """Cuenta el número de pegatinas mal coloreadas (que no coinciden con el color central de su cara)."""
    temp_cube = RubiksCube(cube_state_tuple)
    miscolored_stickers = 0
    solved_colors = {
        'U': 'W', 'F': 'G', 'R': 'R', 'B': 'B', 'L': 'O', 'D': 'Y'
    }

    for face_key, target_color in solved_colors.items():
        for row in temp_cube.faces[face_key]:
            for sticker in row:
                if sticker != target_color:
                    miscolored_stickers += 1
    return miscolored_stickers

def greedy_solve(start_cube, max_depth=7):
    start_time = time.time()

    initial_state_tuple = start_cube.get_state()
    initial_node = Node(initial_state_tuple, depth=0)

    # La cola de prioridad almacena tuplas: (costo_heurístico, id_nodo, nodo)
    priority_queue = [(heuristic(initial_state_tuple), id(initial_node), initial_node)]
    visited = {initial_state_tuple}

    nodes_visited_count = 0

    while priority_queue:
        h_cost, _, current_node = heapq.heappop(priority_queue)
        nodes_visited_count += 1

        if current_node.depth >= max_depth: # Verificación de límite de profundidad
            continue

        temp_cube = RubiksCube(current_node.state)

        if temp_cube.is_solved():
            end_time = time.time()
            execution_time_ms = (end_time - start_time) * 1000
            return {
                "time_ms": execution_time_ms,
                "nodes_visited": nodes_visited_count,
                "solution_path": current_node.get_path()
            }

        for move_name in temp_cube.moves.keys():
            next_cube = RubiksCube(current_node.state)
            next_cube.apply_move(move_name)
            next_state_tuple = next_cube.get_state()

            if next_state_tuple not in visited:
                visited.add(next_state_tuple)
                next_node = Node(next_state_tuple, current_node, move_name, current_node.depth + 1)
                # Empujar con el costo heurístico del siguiente estado
                heapq.heappush(priority_queue, (heuristic(next_state_tuple), id(next_node), next_node))

    end_time = time.time()
    execution_time_ms = (end_time - start_time) * 1000
    return {
        "time_ms": execution_time_ms,
        "nodes_visited": nodes_visited_count,
        "solution_path": [] # No se encontró solución
    }

"""### E. Búsqueda A* (A* Search)

A* es un algoritmo de búsqueda informado que combina el costo del camino recorrido hasta el momento (g) con una estimación heurística del costo restante hasta el objetivo (h). Evalúa los nodos utilizando la función f(n) = g(n) + h(n), lo que le permite encontrar el camino más corto de manera eficiente. Reutilizaremos la misma función heurística definida para Greedy Search.
"""

import heapq
import time

def astar_solve(start_cube, max_depth=7):
    start_time = time.time()

    initial_state_tuple = start_cube.get_state()
    initial_node = Node(initial_state_tuple, depth=0)

    # g_score: costo desde el inicio hasta el estado actual
    g_score = {initial_state_tuple: 0}
    # f_score: g_score + estimación heurística desde el estado actual hasta el objetivo
    f_score = {initial_state_tuple: heuristic(initial_state_tuple)}

    # La cola de prioridad almacena tuplas: (f_score, id_nodo, nodo)
    priority_queue = [(f_score[initial_state_tuple], id(initial_node), initial_node)]

    nodes_visited_count = 0

    while priority_queue:
        current_f_score, _, current_node = heapq.heappop(priority_queue)
        nodes_visited_count += 1

        # Si ya hemos encontrado un camino más barato a este estado, saltar
        if current_f_score > f_score.get(current_node.state, float('inf')):
            continue

        if current_node.depth >= max_depth: # Verificación de límite de profundidad
            continue

        temp_cube = RubiksCube(current_node.state)

        if temp_cube.is_solved():
            end_time = time.time()
            execution_time_ms = (end_time - start_time) * 1000
            return {
                "time_ms": execution_time_ms,
                "nodes_visited": nodes_visited_count,
                "solution_path": current_node.get_path()
            }

        for move_name in temp_cube.moves.keys():
            next_cube = RubiksCube(current_node.state)
            next_cube.apply_move(move_name)
            next_state_tuple = next_cube.get_state()

            # El costo desde el inicio hasta un vecino es el g_score del actual + 1
            tentative_g_score = g_score[current_node.state] + 1

            if tentative_g_score < g_score.get(next_state_tuple, float('inf')):
                # Este camino a next_state es mejor, registrarlo
                g_score[next_state_tuple] = tentative_g_score
                f_score[next_state_tuple] = tentative_g_score + heuristic(next_state_tuple)
                next_node = Node(next_state_tuple, current_node, move_name, current_node.depth + 1)
                heapq.heappush(priority_queue, (f_score[next_state_tuple], id(next_node), next_node))

    end_time = time.time()
    execution_time_ms = (end_time - start_time) * 1000
    return {
        "time_ms": execution_time_ms,
        "nodes_visited": nodes_visited_count,
        "solution_path": [] # No se encontró solución
    }

"""### Comparación de Algoritmos

Para comparar el rendimiento de los algoritmos DFS, BFS, Dijkstra, Greedy Best-First Search y A*, ejecutaremos cada uno en un cubo de Rubik con un nivel de mezcla controlado y registraremos sus métricas.
"""

import pandas as pd

# --- Configuración del Cubo de Prueba ---
scramble_depth = 3 # Puedes ajustar la profundidad de la mezcla aquí (cuidado con valores altos por RAM y tiempo)
max_search_depth = scramble_depth + 2 # Establece un límite de profundidad para los algoritmos

test_cube_comparison = RubiksCube()
scramble_sequence_comparison = []

# Asegurarse de que el cubo esté realmente mezclado antes de probar
while test_cube_comparison.is_solved():
    test_cube_comparison = RubiksCube() # Reiniciar a estado resuelto para un nuevo intento
    scramble_sequence_comparison = test_cube_comparison.scramble(scramble_depth)

print(f"Cubo inicial para comparación (scramble de {scramble_depth} movimientos): {scramble_sequence_comparison}")
test_cube_comparison.display()

# --- Recopilación de Métricas ---
results = {
    'Algoritmo': [],
    'Tiempo (ms)': [],
    'Nodos Visitados': [],
    'Longitud del Camino': []
}

algorithms_to_test = {
    'DFS': dfs_solve,
    'BFS': bfs_solve,
    'Dijkstra': dijkstra_solve,
    'Greedy Search': greedy_solve,
    'A*': astar_solve
}

# Ejecutar y recopilar datos para cada algoritmo
for algo_name, solve_func in algorithms_to_test.items():
    print(f"\nEjecutando {algo_name}...")
    # Crear una copia fresca del cubo mezclado para cada algoritmo
    current_test_cube = RubiksCube(test_cube_comparison.get_state())

    result = solve_func(current_test_cube, max_depth=max_search_depth) # Pasar max_depth

    results['Algoritmo'].append(algo_name)
    results['Tiempo (ms)'].append(f"{result['time_ms']:.2f}")
    results['Nodos Visitados'].append(result['nodes_visited'])
    results['Longitud del Camino'].append(len(result['solution_path']))

    print(f"  Tiempo: {result['time_ms']:.2f} ms, Nodos: {result['nodes_visited']}, Camino: {len(result['solution_path'])} movimientos")
    if result['solution_path']:
        # Verificar si la solución es correcta
        check_cube = RubiksCube(test_cube_comparison.get_state())
        for move in result['solution_path']:
            check_cube.apply_move(move)
        if not check_cube.is_solved():
            print(f"  ¡Advertencia! La solución de {algo_name} no resolvió el cubo.")

# --- Mostrar Resultados en Tabla ---
df_results = pd.DataFrame(results)
print("\n--- Tabla Comparativa de Algoritmos ---")
display(df_results)

"""### Análisis de Resultados de la Comparación de Algoritmos

Basándonos en los resultados de la tabla comparativa (`df_results`):

1.  **¿Qué algoritmo fue el más eficiente en términos de tiempo?**
    El algoritmo más eficiente en términos de tiempo fue **Greedy Search** con un tiempo de ejecución de 1.96 ms, seguido muy de cerca por **A\* Search** con 2.00 ms.

2.  **¿Cuál de los algoritmos visitó la menor cantidad de nodos? Justifique por qué ocurrió esto.**
    Los algoritmos que visitaron la menor cantidad de nodos fueron **Greedy Search** y **A\* Search**, ambos visitando solo 3 nodos. Esto ocurrió porque ambos algoritmos utilizan una función heurística para guiar su búsqueda. En este caso, la heurística (contar pegatinas mal coloreadas) fue muy efectiva para dirigir la búsqueda hacia la solución de manera directa, evitando explorar una gran cantidad de estados irrelevantes. Los algoritmos no informados como DFS, BFS y Dijkstra visitaron muchísimos más nodos porque exploran de forma "ciega" hasta encontrar la solución.

3.  **¿Cuál fue el mejor? ¿Por qué?**
    En este escenario específico (cubo con un scramble de profundidad 3 y un `max_search_depth` de 5), **Greedy Search** y **A\* Search** fueron los mejores. Ambos encontraron la solución en el menor tiempo y visitando la menor cantidad de nodos. Esto se debe a la efectividad de la heurística utilizada para guiar la búsqueda. Mientras que BFS y Dijkstra garantizan la ruta más corta, en este caso, los algoritmos informados con una buena heurística fueron capaces de encontrar una solución óptima (o casi óptima) de forma mucho más rápida y eficiente en el uso de recursos computacionales (menos nodos visitados). DFS, aunque encontró una solución, fue el menos eficiente en tiempo y en nodos visitados para este problema, como es de esperar para un algoritmo no informado en un espacio de búsqueda grande.
"""